spring.application.name=karlo

server.port=9000
# server.address=185.194.216.57
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=jdbc:mysql://localhost:3306/karlodb
spring.datasource.username=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# spring.datasource.password=p0f2R4T3J9U4o1o
spring.datasource.password=*!x96PRaFqbi
# *!x96PRaFqbi

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.generate-ddl=true
spring.jpa.properties.hibernate.hbm2ddl.auto=update
spring.jpa.show-sql=true
spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=600MB
spring.servlet.multipart.max-request-size=600MB


# ==================================== Configuration de gmail ==============================================
spring.mail.host=smtp.dreamhost.com
spring.mail.port=465
spring.mail.username=contact@karlocar.com
spring.mail.password=@Coolschool2021
spring.mail.properties.mail.smtp.ssl.enable=true
spring.mail.properties.mail.smtp.auth=true

# spring.mail.properties.mail.smtp.starttls.enable=false
logging.level.org.springframework.mail=DEBUG

